comment: false

ignore:
  - "prep_data/*"

coverage:
  status:
    project:
      default: false
      r:
        target: auto
        threshold: 1%
        flags:
          - r
      python:
        target: auto
        threshold: 1%
        flags:
          - python
    patch:
      default: false
      r:
        target: auto
        threshold: 1%
        flags:
          - r
      python:
        target: auto
        threshold: 1%
        flags:
          - python
