from geobr.utils import read_geobr_v2


def read_urban_area(
    year: int,
    code_muni: str = "all",
    simplified: bool = False,
    output: str = "gpd",
    show_progress: bool = True,
    cache: bool = True,
    verbose: bool = False,
):
    """ Download spatial data of urbanized areas in Brazil (IBGE).
    
     This function reads the official data on the urban footprint of Brazilian cities.
     Orignal data were generated by Institute of Geography
    and Statistics (IBGE)  For more information about the methodology, see deails at
    https://biblioteca.ibge.gov.br/visualizacao/livros/liv100639.pdf

    Parameters
    ----------
    year : int
        Year of the data.
    code_weighting : str or int
        Municipality code, state abbrev, or ``"all"``.
    simplified, output, show_progress, cache, verbose
        Standard geobr options.
    """

    return read_geobr_v2(
        "urbanareas",
        year,
        code=code_muni,
        simplified=simplified,
        output=output,
        show_progress=show_progress,
        cache=cache,
        verbose=verbose,
    )
