#' Download official data of urbanized areas as an sf object.
#'
#'
#' This function reads the official data of the Brazilian urbanization process in the years 2005 and 2015.
#' Orignal data were generated by IBGE. For more information about the methodology, see deails
#' at https://biblioteca.ibge.gov.br/visualizacao/livros/liv100639.pdf
#'
#'
#'
#' @param year A year number in YYYY format.
#' @export
#' @examples \donttest{
#'
#' library(geobr)
#'
#' # Read all disaster urbanized areas in an specific year
#'   d <- read_urban_area(year=2005)
#'
#' }
#'
#'
#'

library(geobr)

read_urban_area <- function(year=NULL){

  # Get metadata with data addresses
  metadata <- download_metadata()


  # Select geo
  temp_meta <- subset(metadata, geo=="urban_area")

  # Verify year input
  if (is.null(year)){ message("Using latest data available, from year 2015\n")
    year <- 2015
    temp_meta <- subset(temp_meta, year==2015)

  } else if (year %in% temp_meta$year){ temp_meta <- temp_meta[temp_meta[,2] == year, ]

  } else { stop(paste0("Error: Invalid Value to argument 'year'. It must be one of the following: ",
                       paste(unique(temp_meta$year),collapse = " ")))
  }


  # list paths of files to download
  filesD <- as.character(temp_meta$download_path)

  # download files
  temps <- paste0(tempdir(),"/", unlist(lapply(strsplit(filesD,"/"),tail,n=1L)))
  httr::GET(url=filesD, httr::progress(), httr::write_disk(temps, overwrite = T))


  # read sf
  temp_sf <- readr::read_rds(temps)
  return(temp_sf)
}

